steps:
# 1. BUILD the Docker image for the 'server' component
#    - Note the '-f 1209lab2' to use your custom Dockerfile name.
- name: 'gcr.io/cloud-builders/docker'
  id: Build-Image-Server
  args:
  - 'build'
  - '-t'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/heramb-100919492/app:$COMMIT_SHA'
  - '-f'
  - '1209lab2'
  - '.'

# 2. PUSH the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push-Image-Server
  args:
  - 'push'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/heramb-100919492/app:$COMMIT_SHA'

# 3. DEPLOY the new image to Cloud Run (Continuous Deployment)
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy-to-Cloud-Run
  args:
  - 'run'
  - 'deploy'
  - 'lab-2-server' # <-- Change this to your Cloud Run service name!
  - '--image'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/heramb-100919492/app:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated' # Set as needed for public access

# REQUIRED FOR ASSIGNMENT 2 (AND FIXES YOUR ERROR)
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET