version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: 1209lab1
    environment:
      NODE_ENV: production
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Heramb123456789
      POSTGRES_DB: labonedb
    ports:
      - "3000:3000"
    volumes:
      - todo-data:/tmp
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:latest
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: labonedb
      POSTGRES_PASSWORD: Heramb123456789
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  todo-data:
  db-data:
